### ISSUE TITLE
archphile-optimize-rpi: support for uhubctl

### ISSUE THREAD

**Issue by CultofRobots** [archphile/packages#3]
Feature request to add uhubctl support to archphile-optimize-rpi. 
https://github.com/mvp/uhubctl
https://aur.archlinux.org/packages/uhubctl/

Unlike hub-ctrl.c, uhubctl is available in aur and has been updated within the last 5 years.

Probably just need to add something like:
`#[ -x /usr/bin/uhubctl ] && uhubctl <options> `

Thanks.

**Comment by CultofRobots** [comment]
oh and you have a dead link on line 8: 
> 8 # for further information visit http://archphile.org/howto/troubleshooting-pops-and-clicks

**Comment by archphile** [comment]
Thanks for the feedback. 

Both of them fixed (I will need to work on uhubctl options some time soon..).
