### ISSUE TITLE
mpd-archphile: mpd download URL returns 404

### ISSUE THREAD

**Issue by gruentee** [archphile/packages#4]
The download URL is unfortunately not correct anymore as the server's directory doesn't contain the archive in verison 0.21.1:

https://www.musicpd.org/download/mpd/0.20/

Versions >= 0.21 in the `0.21/` directory however seem to have changed the build toolchain such that the `./configure` call in our current PKGBUILD fails, is `configure` is note existent anymore.

**Comment by archphile** [comment]
MPD pkgbuilds for 0.21.x need to be made from scratch.

**Comment by gruentee** [comment]
Alright… you mean PKGBUILDs need to be rewritten?

BTW nice project of yours, I'm currently trying it out and like the ability to fine-tune things in contrast to projects like Volumio.

**Comment by archphile** [comment]
Yes, PKGBUILDS need to be re-written almost from scratch as many things changed with 0.21.x.
