### ISSUE TITLE
mpd-archphile PKGBUILD _opts issues

### ISSUE THREAD

**Issue by CultofRobots** [archphile/packages#6]
### The following are enabled by default and do not need to be specifically enabled in the PKGBUILD:
```
-Dalsa=enabled'
-Dcurl=enabled'
-Daudiofile=enabled'
-Dsndfile=enabled'
-Dffmpeg=enabled'
-Dpipe=true'
-Dwavpack=enabled'
-Dlibmpdclient=enabled'
-Dmad=enabled'
-Dsoxr=enabled'
-Dicu=enabled'
```
Anything listed in [**meson_options.txt**](https://github.com/MusicPlayerDaemon/MPD/blob/master/meson_options.txt) that comes with the source code listed as `type: 'feature'` or `type: 'boolean', value: true` is enabled by default. You only need to specify them when disabling. (They're not very clear about that in the docs.) Pretty sure the only things that need to be specifically enabled are "documentation" and "test" while "zeroconf" is the only one that gives you a choice of options. Everything else is just automatically enabled unless you specifically disable the option. 

### Invalid options:
Line 68 should be `-Diso9660=disabled'` instead of `-Dso9660=disabled'`
Line 92 `'-Dlibwrap=disabled'` can be removed as libwrap was removed from the source

### The Following options are duplicates:
`'-Dmodplug=disabled'` on lines 59 and 87
`'-Doss=disabled'` on lines 70 and 85
`'-Dsidplay=disabled'` on lines 62 and 91
`'-Dwildmidi=disabled'` on lines 78 and 89

**Comment by archphile** [comment]
Many thanks for your comment!

This PKGBUILD is a mess since the introduction of 0.21.x.

I hope that by tomorrow I will have update all my MPD pkgbuilds.

The info you provided is very useful. I will apply everything that you mentioned. 

Regards, 

Mike

**Comment by archphile** [comment]
https://github.com/archphile/packages/commit/dba9039fc8fa59b2619959e7613b7ccaff0d6a2a

**Comment by CultofRobots** [comment]
Welcome. Least I can do since I regularly compare my pkgbuilds to yours just to see if I screwed something up or missed something. And I remember how annoying it was setting up my own pkgbuild after the 0.21.x update. Total nightmare.
