### ISSUE TITLE
update mympd

### ISSUE THREAD

**Issue by satlover1** [archphile/packages#8]
goodmorning,i have mympd version 3.2.1 and i want to update to 5.6.2.what command have i to give?sorry i 'm noob in linux

**Comment by archphile** [comment]
You can't do it with a simple command. 

You will have to use the PKGBUILD and build it but this means that you have some basic knowledge on archlinux packaging.

https://wiki.archlinux.org/index.php/creating_packages

BTW, if you try it, before installing base-devel and other build dependencies, make sure that you have enabled the rollback machine line in /etc/pacman.d/mirrorlist file.
